/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetricsIndexRouteImport } from './routes/metrics/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MetricsSnapshotsRouteImport } from './routes/metrics/snapshots'
import { Route as DataDataIdRouteImport } from './routes/data/$dataId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsSnapshotsRoute = MetricsSnapshotsRouteImport.update({
  id: '/metrics/snapshots',
  path: '/metrics/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDataIdRoute = DataDataIdRouteImport.update({
  id: '/data/$dataId',
  path: '/data/$dataId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data/$dataId': typeof DataDataIdRoute
  '/metrics/snapshots': typeof MetricsSnapshotsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/data/': typeof DataIndexRoute
  '/metrics/': typeof MetricsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data/$dataId': typeof DataDataIdRoute
  '/metrics/snapshots': typeof MetricsSnapshotsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/data': typeof DataIndexRoute
  '/metrics': typeof MetricsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data/$dataId': typeof DataDataIdRoute
  '/metrics/snapshots': typeof MetricsSnapshotsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/data/': typeof DataIndexRoute
  '/metrics/': typeof MetricsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data/$dataId'
    | '/metrics/snapshots'
    | '/dashboard/'
    | '/data/'
    | '/metrics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data/$dataId'
    | '/metrics/snapshots'
    | '/dashboard'
    | '/data'
    | '/metrics'
  id:
    | '__root__'
    | '/'
    | '/data/$dataId'
    | '/metrics/snapshots'
    | '/dashboard/'
    | '/data/'
    | '/metrics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataDataIdRoute: typeof DataDataIdRoute
  MetricsSnapshotsRoute: typeof MetricsSnapshotsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DataIndexRoute: typeof DataIndexRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/metrics'
      fullPath: '/metrics/'
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/snapshots': {
      id: '/metrics/snapshots'
      path: '/metrics/snapshots'
      fullPath: '/metrics/snapshots'
      preLoaderRoute: typeof MetricsSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$dataId': {
      id: '/data/$dataId'
      path: '/data/$dataId'
      fullPath: '/data/$dataId'
      preLoaderRoute: typeof DataDataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataDataIdRoute: DataDataIdRoute,
  MetricsSnapshotsRoute: MetricsSnapshotsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DataIndexRoute: DataIndexRoute,
  MetricsIndexRoute: MetricsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
