/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DataDataIdRouteImport } from './routes/data/$dataId'
import { Route as DashboardVaultRouteImport } from './routes/dashboard/vault'
import { Route as DashboardSnapshotsRouteImport } from './routes/dashboard/snapshots'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDataIdRoute = DataDataIdRouteImport.update({
  id: '/data/$dataId',
  path: '/data/$dataId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVaultRoute = DashboardVaultRouteImport.update({
  id: '/dashboard/vault',
  path: '/dashboard/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSnapshotsRoute = DashboardSnapshotsRouteImport.update({
  id: '/dashboard/snapshots',
  path: '/dashboard/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/snapshots': typeof DashboardSnapshotsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/data/$dataId': typeof DataDataIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/data/': typeof DataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/snapshots': typeof DashboardSnapshotsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/data/$dataId': typeof DataDataIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/data': typeof DataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/snapshots': typeof DashboardSnapshotsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/data/$dataId': typeof DataDataIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/data/': typeof DataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/snapshots'
    | '/dashboard/vault'
    | '/data/$dataId'
    | '/dashboard/'
    | '/data/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/snapshots'
    | '/dashboard/vault'
    | '/data/$dataId'
    | '/dashboard'
    | '/data'
  id:
    | '__root__'
    | '/'
    | '/dashboard/snapshots'
    | '/dashboard/vault'
    | '/data/$dataId'
    | '/dashboard/'
    | '/data/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardSnapshotsRoute: typeof DashboardSnapshotsRoute
  DashboardVaultRoute: typeof DashboardVaultRoute
  DataDataIdRoute: typeof DataDataIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DataIndexRoute: typeof DataIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$dataId': {
      id: '/data/$dataId'
      path: '/data/$dataId'
      fullPath: '/data/$dataId'
      preLoaderRoute: typeof DataDataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vault': {
      id: '/dashboard/vault'
      path: '/dashboard/vault'
      fullPath: '/dashboard/vault'
      preLoaderRoute: typeof DashboardVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/snapshots': {
      id: '/dashboard/snapshots'
      path: '/dashboard/snapshots'
      fullPath: '/dashboard/snapshots'
      preLoaderRoute: typeof DashboardSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardSnapshotsRoute: DashboardSnapshotsRoute,
  DashboardVaultRoute: DashboardVaultRoute,
  DataDataIdRoute: DataDataIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DataIndexRoute: DataIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
