/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ExploreSnapshotsRouteImport } from './routes/explore/snapshots'
import { Route as ExploreDataIdRouteImport } from './routes/explore/$dataId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSnapshotsRoute = ExploreSnapshotsRouteImport.update({
  id: '/explore/snapshots',
  path: '/explore/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreDataIdRoute = ExploreDataIdRouteImport.update({
  id: '/explore/$dataId',
  path: '/explore/$dataId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore/$dataId': typeof ExploreDataIdRoute
  '/explore/snapshots': typeof ExploreSnapshotsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore/$dataId': typeof ExploreDataIdRoute
  '/explore/snapshots': typeof ExploreSnapshotsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/explore': typeof ExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore/$dataId': typeof ExploreDataIdRoute
  '/explore/snapshots': typeof ExploreSnapshotsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore/$dataId'
    | '/explore/snapshots'
    | '/dashboard/'
    | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore/$dataId'
    | '/explore/snapshots'
    | '/dashboard'
    | '/explore'
  id:
    | '__root__'
    | '/'
    | '/explore/$dataId'
    | '/explore/snapshots'
    | '/dashboard/'
    | '/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreDataIdRoute: typeof ExploreDataIdRoute
  ExploreSnapshotsRoute: typeof ExploreSnapshotsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/snapshots': {
      id: '/explore/snapshots'
      path: '/explore/snapshots'
      fullPath: '/explore/snapshots'
      preLoaderRoute: typeof ExploreSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$dataId': {
      id: '/explore/$dataId'
      path: '/explore/$dataId'
      fullPath: '/explore/$dataId'
      preLoaderRoute: typeof ExploreDataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreDataIdRoute: ExploreDataIdRoute,
  ExploreSnapshotsRoute: ExploreSnapshotsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
